import { CalculationTypeInfo, Material } from "./types";

export const CALCULATION_TYPES: CalculationTypeInfo[] = [
  {
    id: "excavation",
    name: "أعمال الحفر",
    nameEn: "Excavation",
    unit: "م3",
    description: "حفر التربة مع حساب معامل الانتفاش",
    icon: "excavation",
    category: "أعمال ترابية",
  },
  {
    id: "backfilling",
    name: "أعمال الردم",
    nameEn: "Backfilling",
    unit: "م3",
    description: "ردم التربة مع حساب معامل الدمك",
    icon: "backfilling",
    category: "أعمال ترابية",
  },
  {
    id: "concrete_footing",
    name: "خرسانة القواعد",
    nameEn: "Concrete Footing",
    unit: "م3",
    description: "خرسانة مسلحة للقواعد مع حساب الحديد والمواد",
    icon: "footing",
    category: "أعمال خرسانية",
  },
  {
    id: "concrete_columns",
    name: "خرسانة الأعمدة",
    nameEn: "Concrete Columns",
    unit: "م3",
    description: "خرسانة مسلحة للأعمدة بكثافة حديد عالية",
    icon: "columns",
    category: "أعمال خرسانية",
  },
  {
    id: "concrete_slabs",
    name: "خرسانة السقوف",
    nameEn: "Concrete Slabs",
    unit: "م3",
    description: "خرسانة مسلحة للبلاطات والسقوف",
    icon: "slabs",
    category: "أعمال خرسانية",
  },
  {
    id: "hordi_slab",
    name: "أسقف هوردي",
    nameEn: "Hordi Slab",
    unit: "م3",
    description: "أسقف هوردي مع حساب البلوك والحديد",
    icon: "hordi",
    category: "أعمال خرسانية",
  },
  {
    id: "plastering",
    name: "أعمال البياض",
    nameEn: "Plastering",
    unit: "م2",
    description: "لياسة داخلية وخارجية",
    icon: "plastering",
    category: "أعمال تشطيبات",
  },
  {
    id: "painting",
    name: "أعمال الدهانات",
    nameEn: "Painting",
    unit: "م2",
    description: "دهانات داخلية وخارجية",
    icon: "painting",
    category: "أعمال تشطيبات",
  },
  {
    id: "tiling",
    name: "أعمال البلاط",
    nameEn: "Tiling",
    unit: "م2",
    description: "تركيب بلاط أرضيات وجدران",
    icon: "tiling",
    category: "أعمال تشطيبات",
  },
  {
    id: "blockwork",
    name: "أعمال البلوك",
    nameEn: "Blockwork",
    unit: "م2",
    description: "بناء جدران بلوك",
    icon: "blockwork",
    category: "أعمال بناء",
  },
  {
    id: "insulation",
    name: "أعمال العزل",
    nameEn: "Insulation",
    unit: "م2",
    description: "عزل مائي وحراري",
    icon: "insulation",
    category: "أعمال تشطيبات",
  },
];

export const DEFAULT_MATERIALS: Material[] = [
  { id: "1", name: "إسمنت", nameEn: "Cement", category: "مواد خرسانية", unit: "طن", basePrice: 1200 },
  { id: "2", name: "رمل", nameEn: "Sand", category: "مواد خرسانية", unit: "م3", basePrice: 150 },
  { id: "3", name: "حصى", nameEn: "Gravel", category: "مواد خرسانية", unit: "م3", basePrice: 200 },
  { id: "4", name: "خرسانة جاهزة", nameEn: "Ready Mix", category: "مواد خرسانية", unit: "م3", basePrice: 450 },
  { id: "5", name: "حديد تسليح", nameEn: "Steel Rebar", category: "حديد", unit: "طن", basePrice: 8000 },
  { id: "6", name: "أسلاك تربيط", nameEn: "Binding Wire", category: "حديد", unit: "كجم", basePrice: 15 },
  { id: "7", name: "بلوك 20سم", nameEn: "Block 20cm", category: "بناء", unit: "قطعة", basePrice: 80 },
  { id: "8", name: "بلوك هوردي", nameEn: "Hordi Block", category: "بناء", unit: "قطعة", basePrice: 120 },
  { id: "9", name: "دهانات", nameEn: "Paint", category: "تشطيبات", unit: "لتر", basePrice: 200 },
  { id: "10", name: "بلاط سيراميك", nameEn: "Ceramic Tiles", category: "تشطيبات", unit: "م2", basePrice: 150 },
  { id: "11", name: "مواد لياسة", nameEn: "Plaster Mix", category: "تشطيبات", unit: "كجم", basePrice: 5 },
  { id: "12", name: "مادة عزل", nameEn: "Insulation Material", category: "عزل", unit: "م2", basePrice: 80 },
  { id: "13", name: "ماء", nameEn: "Water", category: "مواد خرسانية", unit: "لتر", basePrice: 0.5 },
];

export const CURRENCIES = [
  { code: "YER", name: "ريال يمني", symbol: "ر.ي" },
  { code: "SAR", name: "ريال سعودي", symbol: "ر.س" },
  { code: "USD", name: "دولار أمريكي", symbol: "$" },
  { code: "AED", name: "درهم إماراتي", symbol: "د.إ" },
];

export const MATERIAL_RATIOS: Record<string, { materialId: string; qtyPerUnit: number; wastePercent: number }[]> = {
  excavation: [
    { materialId: "1", qtyPerUnit: 0, wastePercent: 0 },
  ],
  backfilling: [
    { materialId: "2", qtyPerUnit: 1.2, wastePercent: 5 },
  ],
  concrete_footing: [
    { materialId: "1", qtyPerUnit: 0.35, wastePercent: 3 },
    { materialId: "2", qtyPerUnit: 0.4, wastePercent: 5 },
    { materialId: "3", qtyPerUnit: 0.8, wastePercent: 5 },
    { materialId: "5", qtyPerUnit: 0.09, wastePercent: 3 },
    { materialId: "6", qtyPerUnit: 0.72, wastePercent: 5 },
    { materialId: "13", qtyPerUnit: 175, wastePercent: 5 },
    { materialId: "4", qtyPerUnit: 1, wastePercent: 3 },
  ],
  concrete_columns: [
    { materialId: "1", qtyPerUnit: 0.4, wastePercent: 3 },
    { materialId: "2", qtyPerUnit: 0.4, wastePercent: 5 },
    { materialId: "3", qtyPerUnit: 0.8, wastePercent: 5 },
    { materialId: "5", qtyPerUnit: 0.13, wastePercent: 3 },
    { materialId: "6", qtyPerUnit: 1.04, wastePercent: 5 },
    { materialId: "13", qtyPerUnit: 175, wastePercent: 5 },
    { materialId: "4", qtyPerUnit: 1, wastePercent: 3 },
  ],
  concrete_slabs: [
    { materialId: "1", qtyPerUnit: 0.35, wastePercent: 3 },
    { materialId: "2", qtyPerUnit: 0.4, wastePercent: 5 },
    { materialId: "3", qtyPerUnit: 0.8, wastePercent: 5 },
    { materialId: "5", qtyPerUnit: 0.11, wastePercent: 3 },
    { materialId: "6", qtyPerUnit: 0.88, wastePercent: 5 },
    { materialId: "13", qtyPerUnit: 175, wastePercent: 5 },
    { materialId: "4", qtyPerUnit: 1, wastePercent: 3 },
  ],
  hordi_slab: [
    { materialId: "1", qtyPerUnit: 0.25, wastePercent: 3 },
    { materialId: "2", qtyPerUnit: 0.3, wastePercent: 5 },
    { materialId: "3", qtyPerUnit: 0.6, wastePercent: 5 },
    { materialId: "5", qtyPerUnit: 0.08, wastePercent: 3 },
    { materialId: "8", qtyPerUnit: 12.5, wastePercent: 5 },
    { materialId: "13", qtyPerUnit: 130, wastePercent: 5 },
    { materialId: "4", qtyPerUnit: 0.7, wastePercent: 3 },
  ],
  plastering: [
    { materialId: "11", qtyPerUnit: 25, wastePercent: 10 },
    { materialId: "2", qtyPerUnit: 0.02, wastePercent: 5 },
    { materialId: "13", qtyPerUnit: 5, wastePercent: 5 },
  ],
  painting: [
    { materialId: "9", qtyPerUnit: 0.4, wastePercent: 10 },
  ],
  tiling: [
    { materialId: "10", qtyPerUnit: 1.1, wastePercent: 5 },
    { materialId: "1", qtyPerUnit: 0.006, wastePercent: 5 },
    { materialId: "2", qtyPerUnit: 0.03, wastePercent: 5 },
  ],
  blockwork: [
    { materialId: "7", qtyPerUnit: 12.5, wastePercent: 5 },
    { materialId: "1", qtyPerUnit: 0.02, wastePercent: 5 },
    { materialId: "2", qtyPerUnit: 0.03, wastePercent: 5 },
  ],
  insulation: [
    { materialId: "12", qtyPerUnit: 1.1, wastePercent: 5 },
  ],
};
